import {Inter} from 'next/font/google';
import 'src/app/globals.css';
import Sidebar from 'src/app/components/common/Sidebar/Sidebar';
import type {ReactNode} from 'react';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
